name: Auto - Apply changes on Merge to production

env:
  AWS_ROLE_ARN: arn:aws:iam::985539765147:role/GithubTerraformEcr

# only trigger on pull request closed events
on:
  pull_request:
    types: [ closed ]
    branches:
      - production

jobs:
  terraform_apply:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    environment: ${{ github.base_ref }}
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest
    name: Auto Apply terraform code to production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Configure Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform
        run: terraform init -backend-config="./${{ github.base_ref }}.config"

      - name: Run Terraform Apply
        run: |
          terraform apply -auto-approve -var-file="${{ github.ref_name }}.tfvars"