name: Auto - Verify & plan branch environment

env:
  AWS_ROLE_ARN: arn:aws:iam::985539765147:role/GithubTerraformEcr

on:
  workflow_dispatch:
  pull_request:
    branches:
      - production

jobs:
  terraform_verify:
    environment: ${{ github.base_ref }}
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest
    name: Auto Verify & plan terraform code for branch environment
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Configure Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform format check
        run: terraform fmt -check -diff -recursive

      - name: Initialize Terraform
        run: terraform init -backend-config="./${{ github.base_ref }}.config"

      - name: Run Terraform Plan
        run: |
          terraform plan -var-file="${{ github.base_ref }}.tfvars" -out plan.tfplan >/dev/null && terraform show plan.tfplan
