name: Manual - Apply changes

env:
  AWS_ROLE_ARN: arn:aws:iam::985539765147:role/GithubTerraformEcr

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Which environment to deploy to
        required: true
        default: production
        options:
          - production

jobs:
  terraform_apply:
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest
    name: Manual apply terraform code to production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Configure Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Terraform format check
        run: terraform fmt -check -diff -recursive

      - name: Initialize Terraform
        run: terraform init -backend-config="./${{ inputs.environment }}.config"

      - name: Run Terraform Apply
        run: |
          terraform apply -auto-approve -var-file="${{ inputs.environment }}.tfvars"
