name: Manual - Apply changes
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Which environment to deploy to
        required: true
        default: production
        options:
          - production

jobs:
  terraform_apply:
    environment: ${{ inputs.environment }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    runs-on: ubuntu-latest
    name: Manual apply terraform code to production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform format check
        run: terraform fmt -check -diff -recursive

      - name: Initialize Terraform
        run: terraform init -backend-config="./${{ inputs.environment }}.config"

      - name: Run Terraform Apply
        run: |
          terraform apply -auto-approve -var-file="${{ inputs.environment }}.tfvars"
